FROM victusfate/python3.8
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /var/www/concierge
COPY ./requirements.txt /var/www/concierge/requirements.txt
RUN pip install -v -r requirements.txt --no-cache

ENV PYTHONPATH='/var/www/concierge/:$PYTHONPATH'
